config/routes.rb
Rails.application.routes.draw do
  resources :playernames
  resources :players
  resources :seasons
  resources :leagues
  get 'welcome/index' => 'index'
  get 'index' => 'welcome#index'

  root 'welcome#index'

end

app/models/playername.rb
class Playername < ActiveRecord::Base
	has_many :players
end

app/controllers/playernames_controller.rb
class PlayernamesController < ApplicationController
  before_action :set_playername, only: [:show, :edit, :update, :destroy]

  # GET /playernames
  # GET /playernames.json
  def index
    reset_session
    @playernames = Playername.all
    session[:leagueid_callback] ||= params[:league_id]
    session[:seasonid_callback] ||= params[:season_id]
  end

  # GET /playernames/1
  # GET /playernames/1.json
  def show
  end

  # GET /playernames/new
  def new
    @playername = Playername.new
  end

  # GET /playernames/1/edit
  def edit
  end

  # POST /playernames
  # POST /playernames.json
  def create
    @playername = Playername.new(playername_params)

    respond_to do |format|
      if @playername.save
        format.html { redirect_to @playername, notice: 'Playername was successfully created.' }
        format.json { render :show, status: :created, location: @playername }
      else
        format.html { render :new }
        format.json { render json: @playername.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playernames/1
  # PATCH/PUT /playernames/1.json
  def update
    respond_to do |format|
      if @playername.update(playername_params)
        format.html { redirect_to @playername, notice: 'Playername was successfully updated.' }
        format.json { render :show, status: :ok, location: @playername }
      else
        format.html { render :edit }
        format.json { render json: @playername.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playernames/1
  # DELETE /playernames/1.json
  def destroy
    @playername.destroy
    respond_to do |format|
      format.html { redirect_to playernames_url, notice: 'Playername was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playername
      @playername = Playername.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playername_params
      params.require(:playername).permit(:name, :team, :amplua, :photolink)
    end
end

app/helpers/playernames_helper.rb
module PlayernamesHelper
end

app/views/playernames/_form.html.erb
<%= form_for(@playername) do |f| %>
  <% if @playername.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playername.errors.count, "error") %> prohibited this playername from being saved:</h2>

      <ul>
      <% @playername.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team %><br>
    <%= f.text_field :team %>
  </div>
  <div class="field">
    <%= f.label :amplua %><br>
    <%= f.text_field :amplua %>
  </div>
  <div class="field">
    <%= f.label :photolink %><br>
    <%= f.text_field :photolink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/playernames/edit.html.erb
<h1>Editing Playername</h1>

<%= render 'form' %>

<%= link_to 'Show', @playername %> |
<%= link_to 'Back', playernames_path %>

app/views/playernames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Playernames database</h1>

<table class="table table-striped sortable">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Team</th>
      <th>Amplua</th>
      <th>Photolink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playernames.each do |playername| %>
      <tr>
        <td><%= playername.id %></td>
        <td><%= playername.name %></td>
        <td><%= playername.team %></td>
        <td><%= playername.amplua %></td>
        <td><%= playername.photolink %></td>
        <td><%= link_to 'Use', new_player_path(:playername_id => playername.id, :season_id => session[:seasonid_callback], :league_id => session[:leagueid_callback]) %></td>
        <td><%= link_to 'Show', playername %></td>
        <td><%= link_to 'Edit', edit_playername_path(playername) %></td>
        <td><%= link_to 'Destroy', playername, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'New Playername', new_playername_path %></h3>

app/views/playernames/new.html.erb
<h1>New Playername</h1>

<%= render 'form' %>

<%= link_to 'Back', playernames_path %>

app/views/playernames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @playername.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @playername.team %>
</p>

<p>
  <strong>Amplua:</strong>
  <%= @playername.amplua %>
</p>

<p>
  <strong>Photolink:</strong>
  <%= @playername.photolink %>
</p>

<%= link_to 'Edit', edit_playername_path(@playername) %> |
<%= link_to 'Back', playernames_path(:season_id => session[:seasonid_callback], :league_id => session[:leagueid_callback]) %>