config/routes.rb
Rails.application.routes.draw do
  resources :playernames
  resources :players
  resources :seasons
  resources :leagues
  get 'welcome/index' => 'index'
  get 'index' => 'welcome#index'

  root 'welcome#index'

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :players, :dependent => :destroy
  belongs_to :league
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    if params[:league_id]
    @seasons = Season.where(:league_id => params[:league_id])
    @currentleague = League.where(:id => params[:league_id]).first
    else
    redirect_to leagues_path
    #@seasons = Season.all
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new(league_id: params[:league_id])
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :league_id, :description)
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size=>"150" %>
  </div>
  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.hidden_field :league_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path(:league_id => @season.league.id) %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h3><%= link_to '< Back to Leagues', leagues_path %></h3>


<h1><%= @currentleague.name %> <br>
Seasons: </h1>


<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.id %></td>
        <td><%= season.name %></td>
        <td><%= season.description %></td>
        <td><%= link_to 'Players', players_path(:id => "", :season_id => season.id, :league_id => params[:league_id]) %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3><%= link_to 'Add New Season', new_season_path(:league_id => params[:league_id]) %></h3>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>League:</strong>
  <%= @season.league.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @season.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @season.description %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path(:league_id => @season.league.id) %>