config/routes.rb
Rails.application.routes.draw do
  resources :playernames
  resources :players
  resources :seasons
  resources :leagues
  get 'welcome/index' => 'index'
  get 'index' => 'welcome#index'

  root 'welcome#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :league
  belongs_to :season
  belongs_to :playername
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    reset_session
    if params[:league_id] and params[:season_id]
    @players = Player.where(:league_id => params[:league_id], :season_id => params[:season_id])
    @currentleague = League.where(:id => params[:league_id]).first
    @currentseason = Season.where(:id => params[:season_id]).first
    else
    redirect_to leagues_path
    #@players = Player.all
    end
    session[:leagueid_callback] ||= params[:league_id]
    session[:seasonid_callback] ||= params[:season_id]

  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new(league_id: params[:league_id], season_id: params[:season_id], :playername_id => params[:playername_id])
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url(league_id: session[:leagueid_callback], season_id: session[:seasonid_callback]), notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:golas, :assists, :league_id, :season_id, :playername_id)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playername_id %><br>
    <%= f.hidden_field :playername_id %>
    <%= @player.playername.name %>
  </div>
  <div class="field">
    <%= f.label :league_id %><br>
    <%= f.hidden_field :league_id %>
    <%= @player.league.name %>
  </div>
  <div class="field">
    <%= f.label :season_id %><br>
    <%= f.hidden_field :season_id %>
    <%= @player.season.name %>
  </div>

  <h3> Input: </h3>
  <div class="field">
    <%= f.label :golas %><br>
    <%= f.number_field :golas %>
  </div>
  <div class="field">
    <%= f.label :assists %><br>
    <%= f.number_field :assists %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path(:season_id => @player.season.id, :league_id => @player.league.id) %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h3><%= link_to '< Back to Seasons', seasons_path(:league_id => params[:league_id])%></h3>

<h1><%= @currentleague.name %>    <%= @currentseason.name %> <br>
Players</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Golas</th>
      <th>Assists</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.playername.name %></td>
        <td><%= player.golas %></td>
        <td><%= player.assists %></td>
        <td><%= player.assists+player.golas*2 %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'Add New Player', playernames_path(:season_id => params[:season_id], :league_id => params[:league_id]) %></h3>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path(:season_id => @player.season.id, :league_id => @player.league.id) %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player Name:</strong>
  <%= @player.playername.name %>
</p>

<p>
  <strong>Golas:</strong>
  <%= @player.golas %>
</p>

<p>
  <strong>Assists:</strong>
  <%= @player.assists %>
</p>

<p>
  <strong>Points:</strong>
  <%= @player.assists+@player.golas*2 %>
</p>

<p>
  <strong>League:</strong>
  <%= @player.league.name %>
</p>

<p>
  <strong>Season:</strong>
  <%= @player.season.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path(:season_id => @player.season.id, :league_id => @player.league.id) %>